### ISSUE TITLE
Prover decision process on making L1 TX for commitment bond depends on gas fees 

### ISSUE THREAD

**Issue by jackhack00** [BlockScience/aztec-gddt#101]
Similar to Sequencer decision process on making L1 TX

Hypothesis: 
Below deprioritized and chosen generlized form: If expected reward is higher than expected cost, user makes TX + Safety margin (0x-10x) (model through scaled beta distribution) (expected safety margin is 3x #hack) 

Long form (deprioritized) 
If Sequencer = Prover, and gas fee = 0, commitment bond being too high may make him not want to do the TX
What is too high? -> Uneconomical with respect to risk of not being able to finalize the block
Risk adjusted Profit (Block reward + profit) must be higher than risk adjusted loss 

If Sequencer is not Prover, and gas fee = 0, same as above (some other factors deprioritized, such as economic censorship to centralize) 

If Sequencer = Prover, and if gas fee is ridicolously high, Sequencer might eat high gas fee to not get slashed

**Comment by jackhack00** [comment]
We go with: 
 First: If expected reward is higher than expected cost, user makes TX + Safety margin (expected safety margin is 3x #hack)
 
 Then (potentially): (0x-10x) (model through scaled beta distribution)

**Comment by jackhack00** [comment]
@eightarmsninebrains 
option A

**Comment by eightarmsninebrains** [comment]
Addressed in Pull Request #109 , specifically commit https://github.com/BlockScience/aztec-gddt/pull/109/commits/3bc240e2f6ebd0c1c8d2e0cde825b2f3b90c997a

**Comment by jackhack00** [comment]
Closed with #109
