### ISSUE TITLE
Requirements for Dynamical Rather than Fixed Time 

### ISSUE THREAD

**Issue by eightarmsninebrains** [BlockScience/aztec-gddt#105]
**Description of Feature:** Phase durations should be minimum and maximum non-negative values of L1 time, with maximum greater than or equal to minimum. 

**Requirements:**
1. A type exists for phase duration  in `types.py` 
2. Relevant phase durations are set before as part of the fields for an AztecModelParams instance. 
3. Phase does not end before minimum time has elapsed.
4. If minimum time has elapsed and relevant signal is sent, model should record variables and move to next phase (largely adapting existing logic). 
5. If maximum time has elapsed and no signal has been sent, model should record variables and move to next phase. This will be a different logical branch than if a relevant signal was sent before maximum time has passed.

**Comment by eightarmsninebrains** [comment]
Addressed in Pull Request #109.

**Comment by jackhack00** [comment]
Closed with #109
