### ISSUE TITLE
Discussion: L1BlocksRange is breaking `test_run.ipynb`

### ISSUE THREAD

**Issue by eightarmsninebrains** [BlockScience/aztec-gddt#108]
The current version of https://github.com/BlockScience/aztec-gddt/tree/ock/feb-19-24/variable-phase-duration

changes the `phase_duration` paramters in `AztecModelParams` with an `L1BlocksRange` class inheriting from `NamedTuple` that uses `min_blocks` and `max_blocks`. 

For some reason, this is leading to an error in line 89 of `sim_run.py`

df = df.assign(**select_config_M_dict(configs, 0, selected_params))
ValueError: Length of values (2) does not match length of index (701)

**FIX:** Can probably be worked around by removing the `L1BlocksRange` and simply hard-coding e.g. `phase_duration_proposal_min_blocks` and `phase_duration_max_blocks` as two separate values. I am more curious what is throwing this issue.

**Comment by danlessa** [comment]
This is actually an issue with `cadCAD.tools`, on which parameters that are passed as lists are incorrectly parsed. I'll commit a workaround.
