### ISSUE TITLE
`gas_fee_l1` and `gas_fee_blob` SUFs consumes from a time-series signal parameter

### ISSUE THREAD

**Issue by danlessa** [BlockScience/aztec-gddt#110]
Both variables should be set to the value from a time-series system parameter

eg. `gas_fee_l1 = params['gas_fee_l1_time_series`][state['timestep']`

**Comment by eightarmsninebrains** [comment]
I am going with an alternate approach for the time being, which enables injecting a time series but does not make it a parameter. Addressed in Pull Request #109

**Comment by jackhack00** [comment]
Closed with #109
