### ISSUE TITLE
We have steady-state time series for `gas_fee_l1` and `gas_fee_blob`

### ISSUE THREAD

**Issue by danlessa** [BlockScience/aztec-gddt#111]
Eg. `gas_fee_l1_time_series = [max(el, 0) for el in np.randn(N_sim_timesteps) * 5 + 30]` 
Eg. `gas_fee_blob_time_series = [max(el, 0) for el in np.randn(N_sim_timesteps) * 5 + 15]`

**Comment by eightarmsninebrains** [comment]
Addressed in Pull Request #109

**Comment by jackhack00** [comment]
Closed with #109
