### ISSUE TITLE
We have sustained shock time series for gas_fee_l1 and gas_fee_blob

### ISSUE THREAD

**Issue by danlessa** [BlockScience/aztec-gddt#112]
eg. `gas_fee_l1 == gas_fee_l1_steady_state_time_series` for the first and last 25% of the simulation timesteps. For the middle 50%, add +100 to it. Same thing to blob gas

**Comment by eightarmsninebrains** [comment]
Addressed in Pull Request #109

**Comment by jackhack00** [comment]
Closed with #109
