### ISSUE TITLE
We have intermitting shock time series for gas_fee_l1 and gas_fee_blob

### ISSUE THREAD

**Issue by danlessa** [BlockScience/aztec-gddt#113]
Eg. `gas_fee_l1 = gas_fee_l1_steady_state_time_series` for the first/last 25% of the simulation time. For the middle half, add a senoid with a 10 block period with a +100 amplitude and offset such that its minimum value is zero (the minimum value of the gas fee should be the steady state value)

**Comment by eightarmsninebrains** [comment]
Addressed in Pull Request #109

**Comment by jackhack00** [comment]
Closed with #109
