### ISSUE TITLE
Replace old cost terms ("cumm_fee_cashback") with param op_costs

### ISSUE THREAD

**Issue by jackhack00** [BlockScience/aztec-gddt#115]
Currently expected payoff checks for fee_cashbacks - since this was deprioritized for simplicity, we replace it with a param op_costs for now. This lets us set a param for somewhat realistic OR logical testing values, letting agents decide whether an action is profitable based on more realistic costs.
Changes:
All three decisions (reveal, commitbond, rollup_proof) take as expected costs op_costs and gas fees (with commitbond also taking blob_gas_fee) 
Param for op_cost 

Later change:
More realistic cost model

**Comment by eightarmsninebrains** [comment]
Addressed in Pull Request #109

**Comment by jackhack00** [comment]
Closed with #109
