### ISSUE TITLE
Rework Block Rewards

### ISSUE THREAD

**Issue by jackhack00** [BlockScience/aztec-gddt#164]
Currently we have a constant block reward per run.
When we test short phase durations, the per block reward is the same, and agents earn a lot.
When we test long phase durations, the per block reward is the same, and agents earn big sad. 

Rework: 
add param `daily_block_reward`
 adapt param `reward_per_block=1`
to
param `reward_per_block=daily_block_reward/sum(all_phase_duration_x_max_blocks)`

Note:
Dynamical Phases don't have pre-defined durations
Setting to max_blocks makes it comparable over both, but prints more bucks when people are faster (which is preferable in reality, but might not be final form of reward mechanism.

**Comment by jackhack00** [comment]
block_rewards need another bunch of assumptions to be set accurately.

since we're working in eth, and reward estimates are usually in % of total supply, we'd need to use some conversion, plus an assumption on total supply, plus an assumption on valuation (or token price) 

that would let us calculate down from 3% / 8% inflation and similar.
Alternatively, assume a reasonable guess and just price in eth

**Comment by danlessa** [comment]
@jackhack00 It is not completely clear to me how the block rewards should be defined.

Do we mean something like:

`RewardPerBlock(Block) = DailyBlockReward(Parameter) / Per-Day Sum over (BlockDurationInL1Blocks(Block) * MaxBlockDurationInL1Blocks(Parameter))`? This does seem somewhat weird to me, as BlockDuration is being double-counted. What seems to make sense is:

`RewardPerBlock(Block) = BlockDurationInL1Blocks(Block) *  [DailyBlockReward(Parameter) / ExpectedBlocksPerDay(Parameter)]`, on which `ExpectedBlocksPerDay(Parameter) = ExpectedL1BlocksPerDay(Parameter) / MaxBlockDuration(Parameter)`. Agree?

**Comment by jackhack00** [comment]
@danlessa 
Yea, the first one seems weird.

I mean the second one, but am unsure about `BlockDurationInL1Blocks(Block)`

`RewardPerBlock(Block) =  [DailyBlockReward(Parameter) / ExpectedBlocksPerDay(Parameter)], on which ExpectedBlocksPerDay(Parameter) = ExpectedL1BlocksPerDay(Parameter) / MaxBlockDuration(Parameter)`
Seems right to me:
The daily reward divided by the expected (longest duration) amount of blocks gives us the per block reward (but still overmints when blocks are done faster, as did old form). 
Not sure what the `BlockDurationInL1Blocks(Block)` multiplier does though! 

* DailyBlockReward (which lets us easily go down from yearly reward, and lets us scale over however many blocks are in the day)
* ExpectedBlocksperDay (lets us define how much to scale)
* ExpectedL1BlocksPerDay (aka 24*3600/12sec) - 1 day in eth l1 block time
* MaxBlockDuration (which lets us comare

**Comment by danlessa** [comment]
@jackhack00 let's go with our definition. Indeed that multiplier don't make sense

**Comment by danlessa** [comment]
@jackhack00 I'll be assuming a daily reward of 32 ETH per day for testing purposes for now.

**Comment by danlessa** [comment]
Implemented by PR #171
