### ISSUE TITLE
Staked Amount still coming back negative

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#172]
![image](https://github.com/BlockScience/aztec-gddt/assets/28468980/1a2584c9-cb4b-4df0-9ea1-d5433c8b003f)

**Comment by SeanMcOwen** [comment]
The ways that it could be dealt with are (and possibly a combo):
Kicking when users are slashed (but this would require adding a joining PSUB probably otherwise there might not be any left eventually)
Adding a "top up" PSUB where the user adds back into their slash by using some of their balance (for example the one in the example issue has enough balance to cover the negative)
Adding guard to this transfer logic I have highlighted
Having it be a pass through where if balance is enough to cover it, it gets used

**Comment by SeanMcOwen** [comment]
With 2000 timesteps and the latest fix it still seems to occur, but I would check on your own run to make sure it wasn't something to do with non-integrated code


<img width="1182" alt="image" src="https://github.com/BlockScience/aztec-gddt/assets/28468980/a07b3224-bd13-4fcd-8ee0-a7d8584af119">

**Comment by danlessa** [comment]
Commit [a8620ec28](https://github.com/BlockScience/aztec-gddt/commit/a8620ec286d89fc6212d9573b201124c0a50c8f2) does increases the test coverage, on which one of the test does runs for 20k. I've noticed that the staked amount test will fail at random runs. Will investigate it.

**Comment by danlessa** [comment]
This seems related to #174

**Comment by danlessa** [comment]
Solved by f128a96d
