### ISSUE TITLE
Token supply might have bug

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#173]
Looking at the token supply, it appears that:

1. There is a huge spike in the first timestep
2. The burnt amount is not tracking
3. Staked is going heavily negative (probabaly related to #172 )

Graph of token supply

![image](https://github.com/BlockScience/aztec-gddt/assets/28468980/60310126-4721-4ff6-a8eb-1e43b5a369f2)

The difference in t=1
![image](https://github.com/BlockScience/aztec-gddt/assets/28468980/f940cdc3-4bfb-4468-8cb0-f4a56a556b33)

The graph of first differences
![image](https://github.com/BlockScience/aztec-gddt/assets/28468980/68ef1dde-99b7-443b-a60e-a6c533fdffcc)

**Comment by SeanMcOwen** [comment]
![image](https://github.com/BlockScience/aztec-gddt/assets/28468980/a1f6d363-825e-4928-9b72-581ee2ebaf3e)

With latest version mostly fixed except it seems that burn is still constant

**Comment by danlessa** [comment]
Seems to be mostly solved by f15b9768a39

One obs is that every once in a while, some amount is un-staked and moved to the circulating supply. This is a potential accountability BUG

**Comment by danlessa** [comment]
I've added a token conservation test on commit 9f4d2925524

The testing is failing

**Comment by danlessa** [comment]
Fixed by commit 602dc4c6c
