### ISSUE TITLE
Implement Sweep over Start Time for the Censoring Series

### ISSUE THREAD

**Issue by danlessa** [BlockScience/aztec-gddt#236]
User Story> we don't have the the sweep, but we have most components. (i.e. the params, the censoring builders, the subset of data we use).
what we don't have is primarily where to start the censoring series from (the entire series is hundreds of thousands of blocks), but I think a reasonable - but not implemented - way would be to pick a random start time for each run, and do lots of monte carlo?

notes:
the source time-series has about 230k elements in L1 time
the constructed time-series has about 10k elements in L1 time
we may want to manually select a subset of the time series (eg. 10 at most, 20%)

1. We provde a list of cherry-picked start times
2. We set the count of time-series to build
3. We set the Maximum % of cherry-picked start times to be included
4. If list 1 is larger than the maximum set of cherry-picked time-series, then select top N until it fulfills that %
5. For all the non cherry picked time series, sample the L1 start time randomly from the source ts (good enough: pseudorandom, excellent: sobol sampling)

**Comment by jackhack00** [comment]
@danlessa 
List of block_numbers, where 'beaverbuild.org' started a spree of at least 13 slots in a row. 
When setting for simulation, we should start at least 200-300 block_numbers before the one listed, to make sure that we don't start every simulation directly with the shock.
Index Builder block_number length_of_slots_in_a_row
132606  beaverbuild.org   19715891.0      13
61674   beaverbuild.org   19433198.0      13
64801   beaverbuild.org   19445274.0      13
65037   beaverbuild.org   19446165.0      13
66268   beaverbuild.org   19450890.0      13
107388  beaverbuild.org   19615545.0      13
106625  beaverbuild.org   19612631.0      13
106067  beaverbuild.org   19610517.0      13
105038  beaverbuild.org   19606581.0      13
104043  beaverbuild.org   19602512.0      13
94642   beaverbuild.org   19564625.0      13
103198  beaverbuild.org   19599046.0      13
117796  beaverbuild.org   19655403.0      13
103677  beaverbuild.org   19601007.0      13
103812  beaverbuild.org   19601571.0      13
114538  beaverbuild.org   19643290.0      14
60098   beaverbuild.org   19427323.0      14
94570   beaverbuild.org   19564317.0      14
77914   beaverbuild.org   19497529.0      14
103237  beaverbuild.org   19599224.0      14
107109  beaverbuild.org   19614434.0      15
68122   beaverbuild.org   19458179.0      15
60948   beaverbuild.org   19430416.0      15
104016  beaverbuild.org   19602401.0      16
89454   beaverbuild.org   19544029.0      17
72507   beaverbuild.org   19475612.0      17
113763  beaverbuild.org   19640428.0      17

**Comment by jackhack00** [comment]
maybe slightly easier: Took the 12 longest sequences, and subtraced 300 from the block_number:
19427023.0
19497229.0
19564017.0
19598924.0
19642990.0
19430116.0
19457879.0
19614134.0
19602101.0
19475312.0
19543729.0
19640128.0

**Comment by danlessa** [comment]
Done by 706e14b
