### ISSUE TITLE
For p_init_process should any of the following be modular? Also what about current time with clock time?

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#261]
In

```
new_process = Process(
            uuid=uuid4(),
            phase=SelectionPhase.pending_proposals,
            leading_sequencer=None,
            uncle_sequencers=None,
            current_phase_init_time=state["time_l1"],
            duration_in_current_phase=0,
            proofs_are_public=False,
            block_content_is_revealed=False,
            commit_bond_is_put_down=False,
            rollup_proof_is_commited=False,
            process_aborted=False,
        )
```

Should proofs_are_public be modular? Nothing else probably needs to be.

Also should there be the current clock time, i.e. 5/13/24 5:00 so that both can be tracked?

**Comment by jackhack00** [comment]
```
proofs_are_public=False,
block_content_is_revealed=False,
commit_bond_is_put_down=False,
rollup_proof_is_commited=False
```
A new process should always be init with these as false. The function that sets them to True should likely be modularized. 

What do you see as benefit from clock time?

**Comment by SeanMcOwen** [comment]
@jackhack00 Only benefit for clock time would be making sure we can have a way to do things like use daily returns of prices. But one can probably get close to real world time with using l1 blocks * average time duration.

So maybe this issue can be scrapped?
