### ISSUE TITLE
Check if gas_fee_l1_acceptable = True is fine for s_transactions_new_proposals

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#282]
Currently is:

gas_fee_l1_acceptable = True #XXX: Temporary economic assumption

We can make a strong assumption but this one feels like a bit too far of an assumption?

**Comment by jackhack00** [comment]
This assumption was only set for the limited censorship sim, where we didn't need the more granular censorship option of setting a threshold after which users find it unreasonable to do L1 transactions. With censorship timeseries, we might instead just rework the profitability test alone to reflect gas / blob gas prices being too high

**Comment by SeanMcOwen** [comment]
Maybe make it a functional parameter and for now have it be a simple always true thing?

**Comment by SeanMcOwen** [comment]
agent expects profit can be something that is modular, but gas_fee_l1_acceptable can be removed as it is a remnant of censorship

**Comment by SeanMcOwen** [comment]
@jackhack00 I am also going to get rid of assertions like these unless you tell me not to:

assert (
                    agent_expects_profit
                ), "REVEAL_CONTENT: Agent should be expecting profit."

**Comment by SeanMcOwen** [comment]
Also spawning a tier 5 issue: #311
