### ISSUE TITLE
Some exogenous processes use timesteps and some use l1 blocks, probably good to standardize

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#283]
I.e. check_for_censorship uses time_l1 versus #275

**Comment by jackhack00** [comment]
agreed, but might want to discuss to make sure 
iirc there was some trip up as we don't have equal timesteps and l1blocks (since we sometimes fastforward)

**Comment by SeanMcOwen** [comment]
Switch to L1 blocks

**Comment by SeanMcOwen** [comment]
Spawning a tier3 issue to do a more rigorous testing to make sure everything is aligned with L1 blocks, i.e. make sure no exogenous series would now break: #313

**Comment by SeanMcOwen** [comment]
- [ ] Switch value_from_param_timeseries_suf to use l1

**Comment by SeanMcOwen** [comment]
Also spawns this tier 5: #314
