### ISSUE TITLE
Why is p_evolve_time_dynamical being used with the state and not the parameters for advancing the l1 blocks

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#291]
def p_evolve_time_dynamical(
    params: AztecModelParams, _2, _3, state: AztecModelState
) -> SignalTime:
    """
    Policy function giving the change in number of blocks.

    Args:
         params (AztecModelParams): The current parameters of the model.

    Returns:
        Signal:
            a dictionary of variables that can be used in an update
    """
    return {"delta_blocks": state["advance_l1_blocks"]}

**Comment by SeanMcOwen** [comment]
This might be fine but need to check because only params are in the docstring

**Comment by jackhack00** [comment]
@danlessa

**Comment by SeanMcOwen** [comment]
Might be an issue with dynamical vs. fixed block duration
