### ISSUE TITLE
Possible Bug: Is transactions not getting reset?

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#301]
In s_transactions, we have the state being updated with the new transactions, but won't that have us double count in the following timesteps stuff like the number of slashes?

**Comment by jackhack00** [comment]
lets discuss

**Comment by SeanMcOwen** [comment]
I can also check it out more deeply myself if it is not an obvious reason

**Comment by SeanMcOwen** [comment]
Not getting cleared, meant for history of all transactions

**Comment by SeanMcOwen** [comment]
Need to check if slashes get double counted, but it might be filtered

**Comment by SeanMcOwen** [comment]
Checked a few places, seems to be fine, will close with branch merge
