### ISSUE TITLE
gas_fee_l1_acceptable is set to always be true

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#303]
This will need to be changed

**Comment by jackhack00** [comment]
All gas_fee_blob_acceptable and gas_fee_l1_acceptable should not be hardcoded, but instead draw from a param (which if not useful, we could just set extremely high)

**Comment by SeanMcOwen** [comment]
Removed this variable per https://github.com/BlockScience/aztec-gddt/issues/282
