### ISSUE TITLE
Expected rewards and expected costs for p_reveal_content are hardcoded

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#304]
Reward hardcoded to 1, cost to 0

**Comment by jackhack00** [comment]
all rewards and costs should be set through params, not hardcoded. 
We currently have one op_costs bucket, which we might slightly rework. Can discuss before implementation

**Comment by SeanMcOwen** [comment]
Currently modular, with an issue here #311 for implementing a basic profitability thing from parameters
