### ISSUE TITLE
For p_reveal_content, gas_fee_blob_acceptable and gas_fee_l1_acceptable are hardcoded as true

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#305]

**Comment by jackhack00** [comment]
similar to commit_bond, this was an adaptation for limited censorship experiment. 
Should instead again be adaptable, ideally through params for sweep possibility. 
All gas_fee_blob_acceptable and gas_fee_l1_acceptable should not be hardcoded, but instead draw from a param (which if not useful, we could just set extremely high)

**Comment by SeanMcOwen** [comment]
Variables removed per #282
