### ISSUE TITLE
Expected rewards and expected costs for p_commit_bond are hardcoded

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#306]
Hardcoded to 1 and 0

**Comment by jackhack00** [comment]
was an adaptation for running the limited censorship experiment.
Ideally, we can again plug in different rewards and costs (potentially as some helper function or regular function) through params or similar

**Comment by SeanMcOwen** [comment]
Currently modular, with an issue here #311 for implementing a basic profitability thing from parameters
