### ISSUE TITLE
Per-phase time is fixed rather than dynamical

### ISSUE THREAD

**Issue by danlessa** [BlockScience/aztec-gddt#83]
In other words, a successful trigger for evolving the phase should result in waiting some time so that the entire phase duration is elapsed

**Comment by jackhack00** [comment]
Boolean functions for dynamical vs fixed phase time.
Discussion might still be needed. 
Assumption for now:
Fixed time means Proposal Phase, Commitment Bond Phase, Reveal Phase, and Regular Proof Phase all end only after time is passed, not after a trigger event. Race Mode ends instantly on first block through hardcoding as current assumption is that Builders will instantly build an empty block. 
Dynamical Time means that only Proposal Phase has a fixed time. Every other phase ends on a trigger action.

**Comment by jackhack00** [comment]
Closed with #109
