### ISSUE TITLE
Refactor: Phase Evolution logic is decoupled from the relevant evolution signal generation

### ISSUE THREAD

**Issue by danlessa** [BlockScience/aztec-gddt#97]
We want to refactor the model logic (PSUBs and SUFs) and blocks so that the following is achieved:

**Requirements**
- [ ]  We have a block on `structure.py` which will be responsible for generating the agents transactions. eg. sending the rollup proof, sending a proposal, etc. We expect this block to update the `transactions`.
  - This block can either re-use the 'Agent Actions' block or be a new one just before it.
- [ ]  The current "Evolve Block Process" block should be completely deterministic. All stochastic elements must be moved to this new/modified block list in 1
  - This may require refactors so that the block process is able to accurately determine if evolution is admissible. Ideally, the evolve process should look at the transactions over the current timestep and determine if the required user action was performed.

**Desirables**

- [ ] We want to generalize / refactor the Process Evolve logic so that patterns are encapsulated to common functions
- [ ] We want to generalize / refactor the User Decision logic so that patterns that drives users to submit a transaction are encapsulated to common functions

**Comment by eightarmsninebrains** [comment]
@danlessa@jackhack00 

 I wanted to double-check this part:
> We have a block on structure.py which will be responsible for generating the agents transactions. eg. sending the rollup proof, sending a proposal, etc. We expect this block to update the transactions.

Do we want it to be possible for agents to consider the existence of other transactions, before making their own transaction decisions?

**Comment by danlessa** [comment]
>Do we want it to be possible for agents to consider the existence of other transactions,

If by other transactions you mean historical txs, then making the model state visible for the decision process already accomplishes that. If we mean txs that weren't included on L1 yet, then we can ignore it.

**Comment by jackhack00** [comment]
@eightarmsninebrains 
@danlessa 
Imo that question only pops up for proposal phase: Will a Sequencer decide to make a proposal if another Sequencer has already made a proposal transaction (in a prior L1 timestep) with a higher score.
(I don't think this has any real impacts, so if we want to simplify we could leave this "ugly" - realistically, a Sequencer would not make a tx if they see another proposal tx with higher score already)
